browser=chrome
base.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
timeout=20
implicitWait=10
explicitWait=20
headless=false
admin.username=Admin
admin.password=admin123
invalid.username=Admin
invalid.password=wrongPassword123
